version: '3'

volumes: 
   postgres_data:
      driver: local

services:
  rabbitmq: 
    image: rabbitmq:3-management
    container_name: health_delivery_message_bus
    expose:
      - 5672
    ports:
      - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: "bus"
        RABBITMQ_DEFAULT_PASS: "bus"  
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: health_delivery_sso
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    command:
        - start-dev
    ports:
        - 8080:8080
  alimentos-db:
    image: postgres:10.5
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
          - '5438:5432'
    volumes:
          - ./postgres-data:/var/lib/postgresql/data 
  alimentos-service:
    image: "conradocabelo/hdl-servicos-alimentos"
    ports:
      - '8001:80'    
    environment:
      - DATA_BASE_CONNECTION="Host=alimentos-db;Port=5432;Username=postgres;Password=postgres;Database=hdl_alimentos"
    depends_on:
      - alimentos-db